---
- name: Configure Slurm Cluster Controller
  hosts: slurm_head
  become: true
  roles: [common, users, firewall, munge, nfs, slurm_common, slurm_controller]

- name: Configure Slurm Worker Nodes
  hosts: slurm_workers
  become: true
  roles: [common, users, firewall, munge, nfs, slurm_common, slurm_worker]
