[slurm_head]
rocky-server ansible_connection=local

[slurm_workers]
rocky-server ansible_connection=local
rocky-minion ansible_user=root
rocky-minion1 ansible_user=root
debian-minion ansible_user=root
ubuntu-minion ansible_user=root

[slurm_cluster:children]
slurm_head
slurm_workers
