---

slurm_partition_name: "debug"

slurmuser_uid: 1100
nfs_server_addr: 192.168.122.225

slurm_nodes:
  - name: "rocky-server"
    cpus: 2
    real_memory: 1451
  - name: "rocky-minion"
    cpus: 2
    real_memory: 1451
  - name: "rocky-minion1"
    cpus: 2
    real_memory: 1451
  - name: "ubuntu-minion"
    cpus: 2
    real_memory: 1711
  - name: "debian-minion"
    cpus: 2
    real_memory: 1717
